// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { GetV1DesktopByIdData, GetV1DesktopByIdResponse, GetV1DesktopByIdError, PostV1DesktopData, PostV1DesktopResponse, PostV1DesktopError, PostV1DesktopByIdStopData, PostV1DesktopByIdStopResponse, PostV1DesktopByIdStopError, PostV1DesktopByIdComputerActionData, PostV1DesktopByIdComputerActionResponse, PostV1DesktopByIdComputerActionError, PostV1DesktopByIdBashActionData, PostV1DesktopByIdBashActionResponse, PostV1DesktopByIdBashActionError } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get details of a specific desktop instance
 * Returns the ID, status, creation timestamp, and timeout timestamp for a given desktop instance.
 */
export const getV1DesktopById = <ThrowOnError extends boolean = false>(options: Options<GetV1DesktopByIdData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetV1DesktopByIdResponse, GetV1DesktopByIdError, ThrowOnError>({
        url: '/v1/desktop/{id}',
        ...options
    });
};

/**
 * Create a new virtual desktop instance
 * Creates a new virtual desktop instance and returns its ID and stream URL
 */
export const postV1Desktop = <ThrowOnError extends boolean = false>(options: Options<PostV1DesktopData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostV1DesktopResponse, PostV1DesktopError, ThrowOnError>({
        url: '/v1/desktop',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Stop a running desktop instance
 * Stops a running desktop instance and cleans up resources
 */
export const postV1DesktopByIdStop = <ThrowOnError extends boolean = false>(options: Options<PostV1DesktopByIdStopData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostV1DesktopByIdStopResponse, PostV1DesktopByIdStopError, ThrowOnError>({
        url: '/v1/desktop/{id}/stop',
        ...options
    });
};

/**
 * Perform an action on the desktop
 * Executes a computer action such as mouse clicks, keyboard input, or screenshots on the desktop
 */
export const postV1DesktopByIdComputerAction = <ThrowOnError extends boolean = false>(options: Options<PostV1DesktopByIdComputerActionData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostV1DesktopByIdComputerActionResponse, PostV1DesktopByIdComputerActionError, ThrowOnError>({
        url: '/v1/desktop/{id}/computer-action',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Execute a bash command on the desktop
 * Runs a bash command on the desktop and returns the command output
 */
export const postV1DesktopByIdBashAction = <ThrowOnError extends boolean = false>(options: Options<PostV1DesktopByIdBashActionData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostV1DesktopByIdBashActionResponse, PostV1DesktopByIdBashActionError, ThrowOnError>({
        url: '/v1/desktop/{id}/bash-action',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};